/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pcars.telas;

import javax.swing.JOptionPane;



/**
 *
 * @author Diego Luz
 */
public class TelaInicial extends javax.swing.JFrame {
    
    public static TelaInicial telaInicial = new TelaInicial();
    
    

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbListClientes = new javax.swing.JButton();
        jbListVeiculos = new javax.swing.JButton();
        jbFecharPrograma = new javax.swing.JButton();
        jbListVendas = new javax.swing.JButton();
        jbCadCliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbCadVeiculos = new javax.swing.JButton();
        jbCadVendas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setText("PCars");

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel2.setText("Listas:");

        jbListClientes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbListClientes.setText("Lista de Clientes");
        jbListClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListClientesActionPerformed(evt);
            }
        });

        jbListVeiculos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbListVeiculos.setText("Lista de Veículos");
        jbListVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListVeiculosActionPerformed(evt);
            }
        });

        jbFecharPrograma.setText("Fechar Programa");
        jbFecharPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharProgramaActionPerformed(evt);
            }
        });

        jbListVendas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbListVendas.setText("Lista Financeira");
        jbListVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListVendasActionPerformed(evt);
            }
        });

        jbCadCliente.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbCadCliente.setText("Cadastrar Clientes");
        jbCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadClienteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel3.setText("Bem-Vindo!");

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel4.setText("Cadastrar:");

        jbCadVeiculos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbCadVeiculos.setText("Cadastrar Veículos");
        jbCadVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadVeiculosActionPerformed(evt);
            }
        });

        jbCadVendas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbCadVendas.setText("Cadastrar Vendas");
        jbCadVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadVendasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbFecharPrograma)
                .addGap(415, 415, 415))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbListVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbListClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbListVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbCadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCadVeiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbCadVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(jLabel3)))
                .addContainerGap(225, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(562, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(286, 286, 286)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCadCliente)
                    .addComponent(jbListClientes))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbListVeiculos)
                    .addComponent(jbCadVeiculos))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbListVendas)
                    .addComponent(jbCadVendas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jbFecharPrograma)
                .addGap(102, 102, 102))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(154, 154, 154)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(348, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbListVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListVeiculosActionPerformed
        // TODO add your handling code here:
        ListaVeiculos listaVeiculos = new ListaVeiculos();
        listaVeiculos.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jbListVeiculosActionPerformed

    private void jbFecharProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharProgramaActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbFecharProgramaActionPerformed

    private void jbListVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListVendasActionPerformed
        // TODO add your handling code here:
        ListaVendas listaVendas = new ListaVendas();
        listaVendas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbListVendasActionPerformed

    private void jbListClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListClientesActionPerformed
        // TODO add your handling code here:
        ListaClientes listaClientes = new ListaClientes();
        listaClientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbListClientesActionPerformed

    private void jbCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadClienteActionPerformed
        // TODO add your handling code here:
        CadastroClientes cadClientes = new CadastroClientes();
        cadClientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbCadClienteActionPerformed

    private void jbCadVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadVeiculosActionPerformed
        // TODO add your handling code here:
        CadastroVeiculos cadVeiculos = new CadastroVeiculos();
        cadVeiculos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbCadVeiculosActionPerformed

    private void jbCadVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadVendasActionPerformed
        // TODO add your handling code here:
        CadastroVendas cadVendas = new CadastroVendas();
        cadVendas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbCadVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCadCliente;
    private javax.swing.JButton jbCadVeiculos;
    private javax.swing.JButton jbCadVendas;
    private javax.swing.JButton jbFecharPrograma;
    private javax.swing.JButton jbListClientes;
    private javax.swing.JButton jbListVeiculos;
    private javax.swing.JButton jbListVendas;
    // End of variables declaration//GEN-END:variables
}
